// Code generated by contractgen. DO NOT EDIT.
package contracttests

import (
	"encoding/json"
	"testing"

	"github.com/example/components/contracts"
	"github.com/example/components/ipc"
)

// RunAlertsContractProviderTests runs all IPC contract tests for the AlertsContract provider.
// factory must return a fresh handler for each subtest.
func RunAlertsContractProviderTests(t *testing.T, factory func() contracts.AlertsContractHandler) {
	t.Helper()

	t.Run("RaiseAlert/request_reply", func(t *testing.T) {
		sock := ipc.TempSocket(t)
		handler := factory()

		ln, err := ipc.Listen(sock)
		if err != nil {
			t.Fatalf("listen: %v", err)
		}

		done := make(chan struct{})
		go func() {
			defer close(done)
			conn, err := ipc.Accept(ln)
			if err != nil {
				return
			}
			defer conn.Close()
			env, err := conn.Receive()
			if err != nil {
				t.Errorf("server receive: %v", err)
				return
			}
			var req contracts.RaiseAlertRequest
			if err := json.Unmarshal(env.Body, &req); err != nil {
				t.Errorf("unmarshal request: %v", err)
				return
			}
			resp, err := handler.HandleRaiseAlert(req)
			var respEnv ipc.Envelope
			if err != nil {
				respEnv = ipc.Envelope{Interaction: env.Interaction, OK: false, Error: err.Error()}
			} else {
				body, _ := json.Marshal(resp)
				respEnv = ipc.Envelope{Interaction: env.Interaction, OK: true, Body: body}
			}
			conn.Send(respEnv)
		}()

		client, err := dialWithRetry(sock, 10)
		if err != nil {
			t.Fatalf("dial: %v", err)
		}
		defer client.Close()

		reqBody, _ := json.Marshal(contracts.RaiseAlertRequest{
			Level: "warn",
			Message: "threshold exceeded",
		})
		err = client.Send(ipc.Envelope{Interaction: "RaiseAlert", Body: reqBody})
		if err != nil {
			t.Fatalf("send request: %v", err)
		}

		respEnv, err := client.Receive()
		if err != nil {
			t.Fatalf("receive response: %v", err)
		}
		if respEnv.Interaction != "RaiseAlert" {
			t.Errorf("interaction mismatch: got %q want %q", respEnv.Interaction, "RaiseAlert")
		}
		if !respEnv.OK {
			t.Fatalf("server returned error: %s", respEnv.Error)
		}

		var fields map[string]interface{}
		if err := json.Unmarshal(respEnv.Body, &fields); err != nil {
			t.Fatalf("unmarshal response body: %v", err)
		}
		assertFieldValue(t, fields, "id", "string", "alert-1")
		assertFieldValue(t, fields, "ok", "bool", "true")

		ln.Close()
		<-done
	})

	t.Run("AlertFired/publish", func(t *testing.T) {
		sock := ipc.TempSocket(t)
		handler := factory()

		ln, err := ipc.Listen(sock)
		if err != nil {
			t.Fatalf("listen: %v", err)
		}

		done := make(chan struct{})
		go func() {
			defer close(done)
			conn, err := ipc.Accept(ln)
			if err != nil {
				return
			}
			defer conn.Close()
			event := handler.TriggerAlertFired()
			body, _ := json.Marshal(event)
			conn.Send(ipc.Envelope{Interaction: "AlertFired", Body: body})
		}()

		client, err := dialWithRetry(sock, 10)
		if err != nil {
			t.Fatalf("dial: %v", err)
		}
		defer client.Close()

		env, err := client.Receive()
		if err != nil {
			t.Fatalf("receive publish: %v", err)
		}
		if env.Interaction != "AlertFired" {
			t.Errorf("interaction mismatch: got %q want %q", env.Interaction, "AlertFired")
		}

		var fields map[string]interface{}
		if err := json.Unmarshal(env.Body, &fields); err != nil {
			t.Fatalf("unmarshal event body: %v", err)
		}
		assertFieldValue(t, fields, "id", "string", "alert-1")
		assertFieldValue(t, fields, "level", "string", "warn")
		assertFieldValue(t, fields, "message", "string", "threshold exceeded")

		ln.Close()
		<-done
	})
}
