// Code generated by contractgen. DO NOT EDIT.
package contracttests

import (
	"encoding/json"
	"testing"

	"github.com/example/components/contracts"
	"github.com/example/components/ipc"
)

// RunTemperatureContractProviderTests runs all IPC contract tests for the TemperatureContract provider.
// factory must return a fresh handler for each subtest.
func RunTemperatureContractProviderTests(t *testing.T, factory func() contracts.TemperatureContractHandler) {
	t.Helper()

	t.Run("GetReading/request_reply", func(t *testing.T) {
		sock := ipc.TempSocket(t)
		handler := factory()

		ln, err := ipc.Listen(sock)
		if err != nil {
			t.Fatalf("listen: %v", err)
		}

		done := make(chan struct{})
		go func() {
			defer close(done)
			conn, err := ipc.Accept(ln)
			if err != nil {
				return
			}
			defer conn.Close()
			env, err := conn.Receive()
			if err != nil {
				t.Errorf("server receive: %v", err)
				return
			}
			var req contracts.GetReadingRequest
			if err := json.Unmarshal(env.Body, &req); err != nil {
				t.Errorf("unmarshal request: %v", err)
				return
			}
			resp, err := handler.HandleGetReading(req)
			var respEnv ipc.Envelope
			if err != nil {
				respEnv = ipc.Envelope{Interaction: env.Interaction, OK: false, Error: err.Error()}
			} else {
				body, _ := json.Marshal(resp)
				respEnv = ipc.Envelope{Interaction: env.Interaction, OK: true, Body: body}
			}
			conn.Send(respEnv)
		}()

		client, err := dialWithRetry(sock, 10)
		if err != nil {
			t.Fatalf("dial: %v", err)
		}
		defer client.Close()

		reqBody, _ := json.Marshal(contracts.GetReadingRequest{
			SensorId: "sensor-1",
		})
		err = client.Send(ipc.Envelope{Interaction: "GetReading", Body: reqBody})
		if err != nil {
			t.Fatalf("send request: %v", err)
		}

		respEnv, err := client.Receive()
		if err != nil {
			t.Fatalf("receive response: %v", err)
		}
		if respEnv.Interaction != "GetReading" {
			t.Errorf("interaction mismatch: got %q want %q", respEnv.Interaction, "GetReading")
		}
		if !respEnv.OK {
			t.Fatalf("server returned error: %s", respEnv.Error)
		}

		var fields map[string]interface{}
		if err := json.Unmarshal(respEnv.Body, &fields); err != nil {
			t.Fatalf("unmarshal response body: %v", err)
		}
		assertFieldValue(t, fields, "value", "float64", "22.5")
		assertFieldValue(t, fields, "unit", "string", "celsius")

		ln.Close()
		<-done
	})

	t.Run("ReadingUpdate/publish", func(t *testing.T) {
		sock := ipc.TempSocket(t)
		handler := factory()

		ln, err := ipc.Listen(sock)
		if err != nil {
			t.Fatalf("listen: %v", err)
		}

		done := make(chan struct{})
		go func() {
			defer close(done)
			conn, err := ipc.Accept(ln)
			if err != nil {
				return
			}
			defer conn.Close()
			event := handler.TriggerReadingUpdate()
			body, _ := json.Marshal(event)
			conn.Send(ipc.Envelope{Interaction: "ReadingUpdate", Body: body})
		}()

		client, err := dialWithRetry(sock, 10)
		if err != nil {
			t.Fatalf("dial: %v", err)
		}
		defer client.Close()

		env, err := client.Receive()
		if err != nil {
			t.Fatalf("receive publish: %v", err)
		}
		if env.Interaction != "ReadingUpdate" {
			t.Errorf("interaction mismatch: got %q want %q", env.Interaction, "ReadingUpdate")
		}

		var fields map[string]interface{}
		if err := json.Unmarshal(env.Body, &fields); err != nil {
			t.Fatalf("unmarshal event body: %v", err)
		}
		assertFieldValue(t, fields, "sensor_id", "string", "sensor-1")
		assertFieldValue(t, fields, "value", "float64", "22.5")
		assertFieldValue(t, fields, "unit", "string", "celsius")
		assertFieldValue(t, fields, "timestamp", "int", "1234567890")

		ln.Close()
		<-done
	})
}
