// Code generated by contractgen. DO NOT EDIT.
package contracts

type RaiseAlertRequest struct {
	Level string `json:"level"`
	Message string `json:"message"`
}

type RaiseAlertResponse struct {
	Id string `json:"id"`
	Ok bool `json:"ok"`
}

type AlertFiredEvent struct {
	Id string `json:"id"`
	Level string `json:"level"`
	Message string `json:"message"`
}

// AlertsContractHandler is implemented by the provider service.
type AlertsContractHandler interface {
	HandleRaiseAlert(req RaiseAlertRequest) (RaiseAlertResponse, error)
	TriggerAlertFired() AlertFiredEvent
}
