// Code generated by contractgen. DO NOT EDIT.
package contracts

type GetReadingRequest struct {
	SensorId string `json:"sensor_id"`
}

type GetReadingResponse struct {
	Value float64 `json:"value"`
	Unit string `json:"unit"`
}

type ReadingUpdateEvent struct {
	SensorId string `json:"sensor_id"`
	Value float64 `json:"value"`
	Unit string `json:"unit"`
	Timestamp int `json:"timestamp"`
}

// TemperatureContractHandler is implemented by the provider service.
type TemperatureContractHandler interface {
	HandleGetReading(req GetReadingRequest) (GetReadingResponse, error)
	TriggerReadingUpdate() ReadingUpdateEvent
}
