package main

import (
	"strings"
	"text/template"
)

var contractsTmpl = template.Must(template.New("contracts").Funcs(template.FuncMap{
	"pascal":  pascal,
	"jsonTag": jsonTag,
	"goType":  goType,
}).Parse(`// Code generated by contractgen. DO NOT EDIT.
package contracts
{{range .Interactions}}{{if eq .Type "request_reply"}}
type {{pascal .Name}}Request struct {
{{- range .Request}}
	{{pascal .Name}} {{goType .Type}} ` + "`" + `json:"{{jsonTag .Name}}"` + "`" + `
{{- end}}
}

type {{pascal .Name}}Response struct {
{{- range .Response}}
	{{pascal .Name}} {{goType .Type}} ` + "`" + `json:"{{jsonTag .Name}}"` + "`" + `
{{- end}}
}
{{else if eq .Type "publish"}}
type {{pascal .Name}}Event struct {
{{- range .Fields}}
	{{pascal .Name}} {{goType .Type}} ` + "`" + `json:"{{jsonTag .Name}}"` + "`" + `
{{- end}}
}
{{end}}{{end}}
// {{.Name}}Handler is implemented by the provider service.
type {{.Name}}Handler interface {
{{- range .Interactions}}{{if eq .Type "request_reply"}}
	Handle{{pascal .Name}}(req {{pascal .Name}}Request) ({{pascal .Name}}Response, error)
{{- else if eq .Type "publish"}}
	Trigger{{pascal .Name}}() {{pascal .Name}}Event
{{- end}}{{end}}
}
`))

// pascal converts snake_case or camelCase to PascalCase.
func pascal(s string) string {
	parts := strings.FieldsFunc(s, func(r rune) bool { return r == '_' || r == '-' })
	var b strings.Builder
	for _, p := range parts {
		if len(p) == 0 {
			continue
		}
		b.WriteString(strings.ToUpper(p[:1]) + p[1:])
	}
	return b.String()
}

// jsonTag returns the original snake_case field name for use as a JSON tag.
func jsonTag(name string) string { return name }

// goType maps YAML type names to Go type names.
func goType(t string) string {
	switch t {
	case "string":
		return "string"
	case "int":
		return "int"
	case "float64":
		return "float64"
	case "bool":
		return "bool"
	default:
		return "interface{}"
	}
}
