package main

import (
	"fmt"
	"text/template"
)

// zeroLiteral returns the Go zero-value literal for a YAML type name.
func zeroLiteral(t string) string {
	switch t {
	case "string":
		return `""`
	case "int":
		return "0"
	case "float64":
		return "0.0"
	case "bool":
		return "false"
	default:
		return "nil"
	}
}

// exampleLiteral returns a Go literal for the given example string and type.
func exampleLiteral(typ, example string) string {
	switch typ {
	case "string":
		return fmt.Sprintf("%q", example)
	default:
		return example // int, float64, bool are valid Go literals as-is
	}
}

var testsTmpl = template.Must(template.New("tests").Funcs(template.FuncMap{
	"pascal":         pascal,
	"goType":         goType,
	"jsonTag":        jsonTag,
	"zeroLiteral":    zeroLiteral,
	"exampleLiteral": exampleLiteral,
}).Parse(`// Code generated by contractgen. DO NOT EDIT.
package contracttests

import (
	"encoding/json"
	"testing"

	"github.com/example/components/contracts"
	"github.com/example/components/ipc"
)

// Run{{.Name}}ProviderTests runs all IPC contract tests for the {{.Name}} provider.
// factory must return a fresh handler for each subtest.
func Run{{.Name}}ProviderTests(t *testing.T, factory func() contracts.{{.Name}}Handler) {
	t.Helper()
{{range .Interactions}}{{if eq .Type "request_reply"}}
	t.Run("{{.Name}}/request_reply", func(t *testing.T) {
		sock := ipc.TempSocket(t)
		handler := factory()

		ln, err := ipc.Listen(sock)
		if err != nil {
			t.Fatalf("listen: %v", err)
		}

		done := make(chan struct{})
		go func() {
			defer close(done)
			conn, err := ipc.Accept(ln)
			if err != nil {
				return
			}
			defer conn.Close()
			env, err := conn.Receive()
			if err != nil {
				t.Errorf("server receive: %v", err)
				return
			}
			var req contracts.{{pascal .Name}}Request
			if err := json.Unmarshal(env.Body, &req); err != nil {
				t.Errorf("unmarshal request: %v", err)
				return
			}
			resp, err := handler.Handle{{pascal .Name}}(req)
			var respEnv ipc.Envelope
			if err != nil {
				respEnv = ipc.Envelope{Interaction: env.Interaction, OK: false, Error: err.Error()}
			} else {
				body, _ := json.Marshal(resp)
				respEnv = ipc.Envelope{Interaction: env.Interaction, OK: true, Body: body}
			}
			conn.Send(respEnv)
		}()

		client, err := dialWithRetry(sock, 10)
		if err != nil {
			t.Fatalf("dial: %v", err)
		}
		defer client.Close()

		reqBody, _ := json.Marshal(contracts.{{pascal .Name}}Request{
{{- range .Request}}
			{{pascal .Name}}: {{if .Example}}{{exampleLiteral .Type .Example}}{{else}}{{zeroLiteral .Type}}{{end}},
{{- end}}
		})
		err = client.Send(ipc.Envelope{Interaction: "{{.Name}}", Body: reqBody})
		if err != nil {
			t.Fatalf("send request: %v", err)
		}

		respEnv, err := client.Receive()
		if err != nil {
			t.Fatalf("receive response: %v", err)
		}
		if respEnv.Interaction != "{{.Name}}" {
			t.Errorf("interaction mismatch: got %q want %q", respEnv.Interaction, "{{.Name}}")
		}
		if !respEnv.OK {
			t.Fatalf("server returned error: %s", respEnv.Error)
		}

		var fields map[string]interface{}
		if err := json.Unmarshal(respEnv.Body, &fields); err != nil {
			t.Fatalf("unmarshal response body: %v", err)
		}
{{range .Response}}{{if .Example}}		assertFieldValue(t, fields, "{{jsonTag .Name}}", "{{.Type}}", "{{.Example}}")
{{else}}		assertField(t, fields, "{{jsonTag .Name}}", "{{.Type}}")
{{end}}{{end}}
		ln.Close()
		<-done
	})
{{else if eq .Type "publish"}}
	t.Run("{{.Name}}/publish", func(t *testing.T) {
		sock := ipc.TempSocket(t)
		handler := factory()

		ln, err := ipc.Listen(sock)
		if err != nil {
			t.Fatalf("listen: %v", err)
		}

		done := make(chan struct{})
		go func() {
			defer close(done)
			conn, err := ipc.Accept(ln)
			if err != nil {
				return
			}
			defer conn.Close()
			event := handler.Trigger{{pascal .Name}}()
			body, _ := json.Marshal(event)
			conn.Send(ipc.Envelope{Interaction: "{{.Name}}", Body: body})
		}()

		client, err := dialWithRetry(sock, 10)
		if err != nil {
			t.Fatalf("dial: %v", err)
		}
		defer client.Close()

		env, err := client.Receive()
		if err != nil {
			t.Fatalf("receive publish: %v", err)
		}
		if env.Interaction != "{{.Name}}" {
			t.Errorf("interaction mismatch: got %q want %q", env.Interaction, "{{.Name}}")
		}

		var fields map[string]interface{}
		if err := json.Unmarshal(env.Body, &fields); err != nil {
			t.Fatalf("unmarshal event body: %v", err)
		}
{{range .Fields}}{{if .Example}}		assertFieldValue(t, fields, "{{jsonTag .Name}}", "{{.Type}}", "{{.Example}}")
{{else}}		assertField(t, fields, "{{jsonTag .Name}}", "{{.Type}}")
{{end}}{{end}}
		ln.Close()
		<-done
	})
{{end}}{{end}}}
`))
